### ISSUE TITLE
installation failed on Windows 10

### ISSUE THREAD

**Issue by leonv024** [franccesco/getaltname#11]
```
Traceback` (most recent call last):
  File "setup.py", line 5, in <module>
    long_description = fh.read()
  File "C:\Users\User1\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2183: character maps to <undefined>
```

Help please. Thanks.

**Comment by franccesco** [comment]
Yup, I'm aware of this issue, I'll be releasing a new version with fix in the next couple of days.

**Comment by franccesco** [comment]
Hi @leonv024 could you try installing it again? It should be fixed by now, remember to have Python >= 3.6, let me know if the problem continues please.

**Comment by leonv024** [comment]
```
leon@pc1 MINGW64 ~/Desktop
$ pip3 install --user gsan
Collecting gsan
  Using cached https://files.pythonhosted.org/packages/41/d3/97d04dedfe956e4fb3b6c3fa6b7c08428300730cad7f206ff568dab61922/gsan-3.0.14.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\leon\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\leon\\AppData\\Local\\Temp\\pip-install-flxoskyz\\gsan\\setup.py'"'"'; __file__='"'"'C:\\Users\\leon\\AppData\\Local\\Temp\\pip-install-flxoskyz\\gsan\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\leon\AppData\Local\Temp\pip-install-flxoskyz\gsan\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\leon\AppData\Local\Temp\pip-install-flxoskyz\gsan\setup.py", line 5, in <module>
        long_description = fh.read()
      File "c:\users\leon\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2162: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

leon@pc1 MINGW64 ~/Desktop
$ py --version
Python 3.8.1
```

:(

**Comment by leonv024** [comment]
works, thanks mate.
