### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by jaikishantulswani** [franccesco/getaltname#2]
Traceback (most recent call last):
  File "getaltname.py", line 40, in <module>
    from modules.get_san import get_san
  File "/home/toor/Desktop/franccesco-getaltname-1a2eff4/modules/get_san.py", line 31
    print(err, end='\n\n')
                  ^
SyntaxError: invalid syntax

**Comment by si9int** [comment]
> print(err, end='\n\n') #python3 print()

I was able to fix this issue by installing all requirement packages via `python-pip3` and executing the script under `python3` env.

**Comment by jaikishantulswani** [comment]
Still getting the same error

**Comment by franccesco** [comment]
If this is a syntax error, are you sure you're using the right python version? What's the output of `python -V`. Make sure to install the latest stable Python version (3.6.5).

**Comment by franccesco** [comment]
Closing this issue due to inactivity.
